//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Cuentas = new HashSet<Cuentas>();
        }
    
        public int Id_Cliente { get; set; }
        public int Cedula { get; set; }
        public string Genero { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Direccion_Fisica { get; set; }
        public int Telefono_Principal { get; set; }
        public Nullable<int> Telefono_Secundario { get; set; }
        public string Correo_Electronico { get; set; }
        public int Tipo_Cliente { get; set; }
        public string Clave_Acceso { get; set; }
    
        public virtual Tipos_Clientes Tipos_Clientes { get; set; }
        public virtual ICollection<Cuentas> Cuentas { get; set; }
    }
}
