//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public Cuentas()
        {
            this.Depositos = new HashSet<Depositos>();
            this.Retiros = new HashSet<Retiros>();
            this.Transferencias = new HashSet<Transferencias>();
            this.Transferencias1 = new HashSet<Transferencias>();
        }
    
        public int Id_Cuenta { get; set; }
        public string Numero_Cuenta { get; set; }
        public int Cliente { get; set; }
        public int Tipo_Cuenta { get; set; }
        public int Moneda { get; set; }
        public decimal Saldo { get; set; }
        public string Estado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Tipos_Cuentas Tipos_Cuentas { get; set; }
        public virtual ICollection<Depositos> Depositos { get; set; }
        public virtual ICollection<Retiros> Retiros { get; set; }
        public virtual ICollection<Transferencias> Transferencias { get; set; }
        public virtual ICollection<Transferencias> Transferencias1 { get; set; }
    }
}
