//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InicioSesion
    {
        public int Id_InicioSesion { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public System.DateTime ultimoIngreso { get; set; }
        public int Id_tipoUsuario { get; set; }
        public int IdCliente { get; set; }
        public string NombreCompleto { get; set; }
    }
}
