//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monedas
    {
        public Monedas()
        {
            this.Cuentas = new HashSet<Cuentas>();
            this.Depositos = new HashSet<Depositos>();
            this.Retiros = new HashSet<Retiros>();
            this.Transferencias = new HashSet<Transferencias>();
        }
    
        public int Id_Moneda { get; set; }
        public string Nombre { get; set; }
        public decimal Tipo_Cambio { get; set; }
        public string Codigo { get; set; }
    
        public virtual ICollection<Cuentas> Cuentas { get; set; }
        public virtual ICollection<Depositos> Depositos { get; set; }
        public virtual ICollection<Retiros> Retiros { get; set; }
        public virtual ICollection<Transferencias> Transferencias { get; set; }
    }
}
