//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retiros
    {
        public int Id_Retiro { get; set; }
        public int Id_Cuenta { get; set; }
        public decimal Monto_Retiro { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Moneda { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Monedas Monedas { get; set; }
    }
}
