//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencias
    {
        public int Id_Transferencia { get; set; }
        public int Id_Cliente { get; set; }
        public int Cuenta_Origen { get; set; }
        public int Cuenta_Destino { get; set; }
        public int Id_Moneda { get; set; }
        public decimal Monto_Transferencia { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Cuentas Cuentas1 { get; set; }
        public virtual Monedas Monedas { get; set; }
    }
}
