//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id_Usuario { get; set; }
        public string Tipo_Usuario { get; set; }
        public int Nombre_Usuario { get; set; }
        public System.DateTime Ultimo_Ingreso { get; set; }
        public string Clave_Acceso { get; set; }
    }
}
